# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before { disable_spawning }
end

def disable_spawning
  allow(Open3).to receive(:capture3)
    .and_raise("Spawning is not permitted in specs.  Please change your spec to use expectations/stubs.")
end

def enable_spawning
  allow(Open3).to receive(:capture3).and_call_original
end

begin
  require 'coveralls'
  Coveralls.wear!
rescue LoadError
end

require 'awesome_spawn'
